import Head from 'next/head'
import Image from 'next/image'
import Layout from '@/components/layout/layout'
import LinkCard from '@/components/links/links'
import styled from "styled-components"
import { selfhostedApplications } from '@/src/data/selfhostedApplications'
import { socials } from '@/src/data/socials'
import { reddit } from '@/src/data/reddit'

const Title = styled.h1`
  color: var(--primary-color);
  margin-bottom: var(--space-sm);
  font-size: 1.5rem;
`

const Container = styled.main`
  margin: var(--space);
`

const Grid = styled.div`
  display: grid;
  padding-inline-start: 0px;
  gap: var(--space);
  grid-template-columns: repeat(0, minmax(0px, 1fr));
  margin-bottom: var(--space);
`

const ServiceGrid = styled.ol`
  display: grid;
  padding: var(--space-sm);
  list-style: none;
  gap: var(--space);
  grid-template-columns: repeat(5, minmax(0px, 1fr));
  border: 2px solid var(--content-bg);

`

const ServiceContainer = styled.div``

const Subtitle = styled.h2`
  color: var(--primary-color);
  font-size: 1.25rem;
  margin: 0 0 var(--space-sm) 0;
`


const BookmarkContainer = styled.div`
  padding: var(--space-sm);
  list-style: none;
  `

const AllBookmarkItems = styled.div`
  display: flex;
  justify-content: flex-start;
  padding-inline-start: 0px;
  margin-top: var(--space);
`

const BookmarkItems = styled.div`
  margin-right: var(--space);
  border-right : 2px solid var(--content-bg);
  min-width: 10%;
  padding: 0.25rem;
`

const BookmarkItemTitle = styled.p`
  font-weight: bold;
  padding: 0.5rem;
`

const BookmarkItem = styled.p`
  padding: 0.5rem;
  transition: 0.2s;
  :hover {
    color: var(--primary-color);
  }
`


export default function Home() {

  return (
    <Layout>
      <Head>
        <title>HomeLab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        {/*<Title>Hi Max!</Title>*/}
        <Grid>

          <ServiceContainer>
            <Subtitle>Dashboard</Subtitle>
            <ServiceGrid>
              {selfhostedApplications.map((application, i) => {
                return <LinkCard item={application} key={i}/>
              })}
            </ServiceGrid>
          </ServiceContainer>

        </Grid>

          
        <BookmarkContainer>
          <Subtitle>Bookmarks</Subtitle>

            <AllBookmarkItems>
              <BookmarkItems>
                <BookmarkItemTitle>Socials</BookmarkItemTitle>
                {socials.map((item, i) => {
                  return (
                    <BookmarkItem>
                      <a key={i} href={item.url} title={item.name} alt={item.name}>{item.name}</a>
                    </BookmarkItem>
                  )
                })}
              </BookmarkItems>              
              
              <BookmarkItems>
                <BookmarkItemTitle>Reddit</BookmarkItemTitle>
                {reddit.map((item, i) => {
                  return (
                    <BookmarkItem>
                      <a key={i} href={item.url} title={item.name} alt={item.name}>{item.name}</a>
                    </BookmarkItem>
                  )
                })}
              </BookmarkItems>
            
            
              <BookmarkItems>
                <BookmarkItemTitle>Email</BookmarkItemTitle>
                    <BookmarkItem>
                      <a href={"https://www.freenet.de/"} title={"freenet"} alt={"Personal Email"}>Personal Email</a>
                    </BookmarkItem>
              </BookmarkItems>

              <BookmarkItems>
                <BookmarkItemTitle>Personal</BookmarkItemTitle>
                    <BookmarkItem>
                      <a href={"https://mxd.codes/cv"} title={"mxd.codes/cv"} alt={"mxd.codes/cv"}>CV</a>
                    </BookmarkItem>
                    <BookmarkItem>
                      <a href={"https://mxd.codes/articles"} title={"mxd.codes/articles"} alt={"mxd.codes/articles"}>Articles</a>
                    </BookmarkItem>
                    <BookmarkItem>
                      <a href={"https://mxd.codes/photos"} title={"mxd.codes/photos"} alt={"mxd.codes/photos"}>Photos</a>
                    </BookmarkItem>
                    <BookmarkItem>
                      <a href={"https://mxd.codes/links"} title={"mxd.codes/links"} alt={"mxd.codes/links"}>Links</a>
                    </BookmarkItem>
                    <BookmarkItem>
                      <a href={"https://mxd.codes/notes"} title={"mxd.codes/notes"} alt={"mxd.codes/notes"}>Notes</a>
                    </BookmarkItem>
              </BookmarkItems>

              <BookmarkItems>
                <BookmarkItemTitle>Banking</BookmarkItemTitle>
                    <BookmarkItem>
                      <a href={"https://www.dkb.de/banking"} title={"DKB"} alt={"DKB"}>DKB</a>
                    </BookmarkItem>
                    <BookmarkItem>
                      <a href={"https://businesstravelportal.airplus.com/"} title={"AirPlus Portal"} alt={"AirPlus Portal"}>AirPlus Portal</a>
                    </BookmarkItem>
                    <BookmarkItem>
                      <a href={"https://de.scalable.capital/broker/success"} title={"Scalable"} alt={"Scalable"}>Scalable</a>
                    </BookmarkItem>
                    <BookmarkItem>
                      <a href={"https://portal.ebase.com/(e1)/finvesto/login?eox=r"} title={"Finvesto"} alt={"Finvesto"}>Finvesto</a>
                    </BookmarkItem>
              </BookmarkItems>


              <BookmarkItems>
                <BookmarkItemTitle>Cloud-Computing</BookmarkItemTitle>
                    <BookmarkItem>
                      <a href={"https://www.customercontrolpanel.de/"} title={"Netcup CCP"} alt={"Netcup CCP"}>Netcup CCP</a>
                    </BookmarkItem>
                    <BookmarkItem>
                      <a href={"https://www.servercontrolpanel.de/SCP/Home?site_key=gZGpUDBAgr61zWa5zx8PNPQ4Utw64UAZ"} title={"Netcup SCP"} alt={"Netcup SCP"}>Netcup SCP</a>
                    </BookmarkItem>
                    <BookmarkItem>
                      <a href={"https://aws.amazon.com"} title={"AWS"} alt={"AWS"}>AWS</a>
                    </BookmarkItem>
                    <BookmarkItem>
                      <a href={"https://cloud.google.com"} title={"GCP"} alt={"GCP"}>GCP</a>
                    </BookmarkItem>
                    <BookmarkItem>
                      <a href={"https://azure.microsoft.com"} title={"Azure"} alt={"Azure"}>Azure</a>
                    </BookmarkItem>
              </BookmarkItems>

              <BookmarkItems>
                <BookmarkItemTitle>Other</BookmarkItemTitle>
                    <BookmarkItem>
                      <a href={"https://web.whatsapp.com/"} title={"Whatsapp Web"} alt={"Whatsapp Web"}>Whatsapp Web</a>
                    </BookmarkItem>
                    <BookmarkItem>
                      <a href={"https://indieweb.org/"} title={"IndieWeb"} alt={"IndieWeb"}>IndieWeb</a>
                    </BookmarkItem>
                    <BookmarkItem>
                      <a href={"https://webmention.io/api/mentions.html?token=rxwJcoKxWCd9n3NA9SoxeQ"} title={"Webmentions"} alt={"Webmentions"}>Webmentions</a>
                    </BookmarkItem>
              </BookmarkItems>

            </AllBookmarkItems>


          </BookmarkContainer>
        


      </Container>

      <footer>
      </footer>
    </Layout>
  )
}
