import Head from 'next/head'
import Image from 'next/image'
import Layout from '@/components/layout/layout'
import LinkCard from '@/components/links/links'
import styled from "styled-components"
import { applications, media, website, tools } from 'links'

const Title = styled.h1`
  color: var(--primary-color);
  text-align: center;
  margin: 2rem 1rem;
  font-size: 2rem;
`

const Container = styled.main`
  margin: var(--space-lg) var(--space) var(--space) var(--space);
`

const Grid = styled.div`
  display: grid;
  padding-inline-start: 0px;
  gap: var(--space);
  grid-template-columns: repeat(2, minmax(0px, 1fr));
`

const ServiceGrid = styled.ol`
  display: grid;
  padding: var(--space-sm);
  list-style: none;
  gap: var(--space);
  grid-template-columns: repeat(2, minmax(0px, 1fr));
  border: 2px solid var(--content-bg);

`



const ServiceContainer = styled.div``

const Subtitle = styled.h2`
  color: var(--primary-color);
  font-size: 1.5rem;
  text-align: center;
  margin: 0 0 var(--space-sm) 0;
`

export default function Home() {

  return (
    <Layout>
      <Head>
        <title>HomeLab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Grid>
          <ServiceContainer>
            <Subtitle>Applications</Subtitle>
            <ServiceGrid>
              {applications.map((application, i) => {
                return <LinkCard item={application} key={i}/>
              })}
            </ServiceGrid>
          </ServiceContainer>
          
          <ServiceContainer>
            <Subtitle>Media</Subtitle>
            <ServiceGrid>
              {media.map((media, i) => {
                return <LinkCard item={media} key={i}/>
              })}
            </ServiceGrid>
          </ServiceContainer>

          <ServiceContainer>
            <Subtitle>Website</Subtitle>
            <ServiceGrid>
              {website.map((item, i) => {
                return <LinkCard item={item} key={i}/>
              })}
            </ServiceGrid>
          </ServiceContainer>

          <ServiceContainer>
            <Subtitle>Tools</Subtitle>
            <ServiceGrid>
              {tools.map((item, i) => {
                return <LinkCard item={item} key={i}/>
              })}
            </ServiceGrid>
          </ServiceContainer>

        </Grid>

      </Container>

      <footer>
      </footer>
    </Layout>
  )
}
